[package]
name = "reservation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.8"
abi = { version = "0.1.0", path = "../abi" }
sqlx = { version = "0.7.4", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
chrono = { version = "0.4.38", features = ["serde"] }
[dev-dependencies]
sqlx-database-tester = {version="0.4.2", features=["runtime-tokio"]}
tokio = { version = "1.37.0", features = ["full"] }